
import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import panamahitek.Arduino.PanamaHitek_Arduino;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juan Pedro Gil
 */
public class Interfaz extends javax.swing.JFrame {
    PanamaHitek_Arduino arduino=new PanamaHitek_Arduino();
    boolean bi,bd, bI, bD, b1, b2;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        bi=bd=bI=bD=b1=b2=false;
        this.setLocationRelativeTo(this);
        txtTiempo.setText("Segundos");
        txtTiempo.setForeground(Color.LIGHT_GRAY);
        this.setResizable(false);
        Dimension dim = panelPrincipal.getSize();
        this.setSize(dim);
        panelPrincipal.setBackground(Color.yellow);
        this.setTitle("PetFood");   
        cImagen(logo);
        try {
            arduino.arduinoTX("COM4", 9600);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        btnEncender1 = new javax.swing.JButton();
        btnEncender2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        btnTiempo = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        giroIzq1 = new javax.swing.JButton();
        giroDer1 = new javax.swing.JButton();
        giroIzq2 = new javax.swing.JButton();
        giroDer2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEncender1.setBackground(new java.awt.Color(249, 66, 15));
        btnEncender1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEncender1.setText("Encender motor 1");
        btnEncender1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEncender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncender1ActionPerformed(evt);
            }
        });

        btnEncender2.setBackground(new java.awt.Color(249, 66, 15));
        btnEncender2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEncender2.setText("Encender motor 2");
        btnEncender2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEncender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncender2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Tiempo para la comida");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTiempo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTiempo.setForeground(new java.awt.Color(51, 0, 255));
        txtTiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTiempo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTiempo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTiempoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTiempoFocusLost(evt);
            }
        });

        btnTiempo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTiempo.setForeground(new java.awt.Color(51, 51, 255));
        btnTiempo.setText("Asignar Tiempo");
        btnTiempo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiempoActionPerformed(evt);
            }
        });

        logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        giroIzq1.setBackground(new java.awt.Color(249, 66, 15));
        giroIzq1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        giroIzq1.setText("Izq");
        giroIzq1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        giroIzq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giroIzq1ActionPerformed(evt);
            }
        });

        giroDer1.setBackground(new java.awt.Color(249, 66, 15));
        giroDer1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        giroDer1.setText("Der");
        giroDer1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        giroDer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giroDer1ActionPerformed(evt);
            }
        });

        giroIzq2.setBackground(new java.awt.Color(249, 66, 15));
        giroIzq2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        giroIzq2.setText("Izq");
        giroIzq2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        giroIzq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giroIzq2ActionPerformed(evt);
            }
        });

        giroDer2.setBackground(new java.awt.Color(249, 66, 15));
        giroDer2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        giroDer2.setText("Der");
        giroDer2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        giroDer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giroDer2ActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 0, 0));
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnEncender2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(giroIzq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnEncender1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(giroIzq1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(giroDer1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(giroDer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEncender1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(giroIzq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(giroDer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEncender2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(giroIzq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(giroDer2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cImagen(JLabel label){
        ImageIcon icono = new ImageIcon("src/Imagenes/logo.png");
        label.setIcon(icono); 
    }
    private boolean isNumeric(String valor){
        for (int i = 0; i < valor.length(); i++) {
            if (valor.charAt(i)==46 || valor.charAt(i)==45) {
                
            }else{
                if (valor.charAt(i)<48 || valor.charAt(i)>57) {
                    return false;
                }
            }
        }
        return true;
    }
    private void btnEncender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncender1ActionPerformed
        try {
            if (!b1) {
                btnEncender1.setBackground(Color.green);
                b1=true;
            }else{
                btnEncender1.setBackground(new Color(249,66,15));
                giroIzq1.setBackground(new Color(249,66,15));
                giroDer1.setBackground(new Color(249,66,15));
                b1=false;
                bi=false;
                bd=false;
            }
            arduino.sendData("1");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEncender1ActionPerformed

    private void btnEncender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncender2ActionPerformed
        try {            
            if (!b2) {
                btnEncender2.setBackground(Color.green);
                b2=true;
            }else{
                btnEncender2.setBackground(new Color(249,66,15));
                giroIzq2.setBackground(new Color(249,66,15));
                giroDer2.setBackground(new Color(249,66,15));
                b2=false;
                bI=false;
                bD=false;
            }
            arduino.sendData("2");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEncender2ActionPerformed

    private void btnTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiempoActionPerformed
        try {
            if (!txtTiempo.getText().equals("") && isNumeric(txtTiempo.getText())) {
                float valor=Float.parseFloat(txtTiempo.getText());
                if (valor>0) {
                    arduino.sendData(txtTiempo.getText());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTiempoActionPerformed

    private void giroIzq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giroIzq1ActionPerformed
        // TODO add your handling code here:
        try {
            if (!bi && b1) {
                giroIzq1.setBackground(Color.green);
                giroDer1.setBackground(new Color(249,66,15));
                bd=false;
                bi=true;
            }else{
                giroIzq1.setBackground(new Color(249,66,15));
                bi=false;
            }
            arduino.sendData("i");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_giroIzq1ActionPerformed

    private void giroDer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giroDer1ActionPerformed
        // TODO add your handling code here:
        try {
            if (!bd && b1) {
                giroDer1.setBackground(Color.green);
                giroIzq1.setBackground(new Color(249,66,15));
                bi=false;
                bd=true;
            }else{
                giroDer1.setBackground(new Color(249,66,15));
                bd=false;
            }
            arduino.sendData("d");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_giroDer1ActionPerformed

    private void giroIzq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giroIzq2ActionPerformed
        // TODO add your handling code here:
        try {
            if (!bI && b2) {
                giroIzq2.setBackground(Color.green);
                giroDer2.setBackground(new Color(249,66,15));
                bD=false;
                bI=true;
            }else{
                giroIzq2.setBackground(new Color(249,66,15));
                bI=false;
            }
            arduino.sendData("I");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_giroIzq2ActionPerformed

    private void giroDer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giroDer2ActionPerformed
        // TODO add your handling code here:
        try {
            if (!bD && b2) {
                giroDer2.setBackground(Color.green);
                giroIzq2.setBackground(new Color(249,66,15));
                bI=false;
                bD=true;
            }else{
                giroDer2.setBackground(new Color(249,66,15));
                bD=false;
            }
            arduino.sendData("D");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_giroDer2ActionPerformed

    private void txtTiempoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTiempoFocusGained
        // TODO add your handling code here:
        if (txtTiempo.getText().equals("Segundos")) {            
            txtTiempo.setText("");
        }
        txtTiempo.setForeground(Color.blue);
    }//GEN-LAST:event_txtTiempoFocusGained

    private void txtTiempoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTiempoFocusLost
        // TODO add your handling code here:
        if (txtTiempo.getText().equals("")) {
            txtTiempo.setText("Segundos");
            txtTiempo.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtTiempoFocusLost

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        // TODO add your handling code here:
        try {
            arduino.sendData("s");
            giroIzq2.setBackground(new Color(249,66,15));
            giroIzq1.setBackground(new Color(249,66,15));
            giroDer2.setBackground(new Color(249,66,15));
            giroDer1.setBackground(new Color(249,66,15));
            btnEncender1.setBackground(new Color(249,66,15));
            btnEncender2.setBackground(new Color(249,66,15));
            b1=b2=bi=bd=bI=bD=false;
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncender1;
    private javax.swing.JButton btnEncender2;
    private javax.swing.JButton btnTiempo;
    private javax.swing.JButton giroDer1;
    private javax.swing.JButton giroDer2;
    private javax.swing.JButton giroIzq1;
    private javax.swing.JButton giroIzq2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
